#!/bin/bash
# generate dot files and render into png

java -jar antlr-4.7.2-complete.jar -atn little_grammar.g4

for i in ./little_grammar*.dot
do
    filename=${i%.*}
    echo generating ${filename}
    dot -Tpng ${filename}.dot -o images/${filename}.png
done

rm -rf *.class
rm -rf little_grammar*.java
rm -rf *.tokens
rm -rf *.interp
rm ./*.dot